version: "3.8"
services:
  wg-easy:
    environment:
      - WG_HOST=!!!!!!!!!!!!!
      - PASSWORD=!!!!!!!!!!!!!!
    env_file:
      - wg_pre_up
    image: weejewel/wg-easy
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx
    hostname: nginx
    volumes:
      - ~/.nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.nginx/ssl/:/etc/nginx/ssl/
    ports:
      - "51821:51821/tcp"
    restart: unless-stopped
  squid:
    image: ubuntu/squid:latest
    container_name: squid
    hostname: squid
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ~/.squid/squid.conf:/etc/squid/squid.conf
    restart: always